from __future__ import annotations

import html
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

from aio_fleet.manifest import RepoConfig
from aio_fleet.release import next_aio_release_version, next_semver_release_version


def generated_note(changelog: Path | str = "CHANGELOG.md") -> str:
    name = changelog.name if isinstance(changelog, Path) else str(changelog)
    return f"- Generated from {name} during release preparation. Do not edit manually."


GENERATED_NOTE = generated_note()


def normalize_markdown_changelog(changelog: Path) -> None:
    """Keep generated release sections compatible with Prettier markdown rules."""
    normalized: list[str] = []
    previous_blank = False
    for line in changelog.read_text().splitlines():
        if line.strip():
            normalized.append(line.rstrip())
            previous_blank = False
        elif not previous_blank:
            normalized.append("")
            previous_blank = True

    spaced: list[str] = []
    for line in normalized:
        if line.startswith("## ") and spaced and spaced[-1] != "":
            spaced.append("")
        spaced.append(line)
        if line.startswith(("## ", "### ")):
            spaced.append("")

    final: list[str] = []
    previous_blank = False
    for line in spaced:
        if line:
            final.append(line)
            previous_blank = False
        elif not previous_blank:
            final.append("")
            previous_blank = True

    changelog.write_text("\n".join(final).rstrip() + "\n")


@dataclass(frozen=True)
class ReleasePlan:
    version: str
    changelog_path: Path
    xml_paths: list[Path]
    cliff_config: str
    component: str = "aio"
    release_suffix: str = "aio"
    release_tag_prefix: str = ""
    registry_revision_path: Path | None = None
    registry_revision_arg: str = ""
    registry_revision_value: str = ""


def render_git_cliff_config(
    repo: RepoConfig, *, release_suffix: str = "aio", release_tag_prefix: str = ""
) -> str:
    tag_pattern = (
        "^v?[0-9]+\\.[0-9]+\\.[0-9]+$"
        if repo.publish_profile == "template"
        else (
            f"^{re.escape(release_tag_prefix)}v?[0-9].*-"
            f"{re.escape(release_suffix)}\\.[0-9]+$"
        )
    )
    return f'''[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{{% if version %}}## {{{{ version }}}} - {{{{ timestamp | date(format="%Y-%m-%d") }}}}{{% else %}}## Unreleased{{% endif %}}

{{% for group, commits in commits | group_by(attribute="group") %}}
### {{{{ group }}}}

{{% for commit in commits %}}
- {{{{ commit.message | split(pat="\\n") | first | trim | upper_first }}}}
{{% endfor %}}
{{% if not loop.last %}}
{{% endif %}}
{{% endfor %}}
"""
trim = true
footer = "<!-- generated by git-cliff -->"

[git]
conventional_commits = true
filter_unconventional = false
require_conventional = false
split_commits = false
protect_breaking_commits = true
tag_pattern = '{tag_pattern}'
sort_commits = "oldest"
commit_preprocessors = [{{ pattern = " \\\\(#\\\\d+\\\\)$", replace = "" }}]
commit_parsers = [
  {{ message = "^Merge pull request", skip = true }},
  {{ message = "^chore\\\\(release\\\\):", skip = true }},
  {{ message = "^feat", group = "Features" }},
  {{ message = "^fix", group = "Fixes" }},
  {{ message = "^perf", group = "Performance" }},
  {{ message = "^refactor", group = "Refactors" }},
  {{ message = "^docs?", group = "Documentation" }},
  {{ message = "^ci", group = "CI" }},
  {{ message = "^test", group = "Tests" }},
  {{ message = "^build", group = "Build" }},
  {{ message = "^chore\\\\(deps", group = "Dependency Updates" }},
  {{ message = "^chore", group = "Maintenance" }},
  {{ message = "^revert", group = "Reverts" }},
  {{ message = "^[A-Z].*", group = "Other Changes" }},
]
'''


def write_temp_git_cliff_config(
    repo: RepoConfig, *, release_suffix: str = "aio", release_tag_prefix: str = ""
) -> Path:
    handle = tempfile.NamedTemporaryFile(
        "w", prefix=f"{repo.name}-git-cliff-", suffix=".toml", delete=False
    )
    with handle:
        handle.write(
            render_git_cliff_config(
                repo,
                release_suffix=release_suffix,
                release_tag_prefix=release_tag_prefix,
            )
        )
    return Path(handle.name)


def build_release_plan(repo: RepoConfig, *, component: str = "aio") -> ReleasePlan:
    config = component_config(repo, component)
    release_suffix = str(config.get("release_suffix", "aio"))
    release_tag_prefix = str(config.get("release_tag_prefix", "") or "")
    version = _next_version(repo, component=component)
    changelog_path = repo.path / str(config.get("release_changelog", "CHANGELOG.md"))
    revision_arg = str(config.get("registry_revision_arg", "") or "").strip()
    revision_value = (
        _version_revision(version, release_suffix=release_suffix)
        if revision_arg
        else ""
    )
    return ReleasePlan(
        version=version,
        changelog_path=changelog_path,
        xml_paths=[
            repo.path / path for path in _release_xml_sources(repo, component=component)
        ],
        cliff_config=render_git_cliff_config(
            repo,
            release_suffix=release_suffix,
            release_tag_prefix=release_tag_prefix,
        ),
        component=component,
        release_suffix=release_suffix,
        release_tag_prefix=release_tag_prefix,
        registry_revision_path=(
            repo.path / str(config.get("dockerfile", "Dockerfile"))
            if revision_arg and revision_value
            else None
        ),
        registry_revision_arg=revision_arg,
        registry_revision_value=revision_value,
    )


def update_registry_revision_arg(plan: ReleasePlan) -> bool:
    if (
        plan.registry_revision_path is None
        or not plan.registry_revision_arg
        or not plan.registry_revision_value
    ):
        return False
    pattern = re.compile(
        rf"^ARG {re.escape(plan.registry_revision_arg)}=(?P<value>.+)$",
        flags=re.MULTILINE,
    )
    content = plan.registry_revision_path.read_text()
    matches = list(pattern.finditer(content))
    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one ARG {plan.registry_revision_arg} in "
            f"{plan.registry_revision_path}"
        )
    updated = pattern.sub(
        f"ARG {plan.registry_revision_arg}={plan.registry_revision_value}",
        content,
        count=1,
    )
    plan.registry_revision_path.write_text(updated)
    return updated != content


def update_template_changes(
    *,
    version: str,
    changelog: Path,
    template: Path,
) -> None:
    notes = extract_release_notes(version, changelog)
    body = build_changes_body(version, notes, changelog)
    content = template.read_text()
    updated, count = re.subn(
        r"<Changes>.*?</Changes>",
        f"<Changes>{encode_for_template(body)}</Changes>",
        content,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise ValueError(f"Expected exactly one <Changes> block in {template}")
    template.write_text(updated)


def extract_release_notes(version: str, changelog: Path) -> str:
    heading = re.compile(
        rf"^##\s+(?:\[{re.escape(version)}\]\([^)]+\)|{re.escape(version)})(?:\s+-\s+.+)?$"
    )
    next_heading = re.compile(r"^##\s+")
    lines = changelog.read_text().splitlines()
    start = None
    for idx, line in enumerate(lines):
        if heading.match(line.strip()):
            start = idx + 1
            break
    if start is None:
        raise ValueError(f"Unable to find release section for {version} in {changelog}")
    end = len(lines)
    for idx in range(start, len(lines)):
        if next_heading.match(lines[idx].strip()):
            end = idx
            break
    notes = "\n".join(lines[start:end]).strip()
    if not notes:
        raise ValueError(f"Release section for {version} in {changelog} is empty")
    return notes


def release_section_exists(version: str, changelog: Path) -> bool:
    try:
        extract_release_notes(version, changelog)
    except (OSError, ValueError):
        return False
    return True


def build_changes_body(version: str, notes: str, changelog: Path) -> str:
    lines = [release_heading(version, changelog), generated_note(changelog)]
    for line in notes.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("<!--") and stripped.endswith("-->"):
            continue
        if re.match(r"^\[[^\]]+\]:\s+https?://", stripped):
            continue
        if stripped.startswith(("Full Changelog:", "## ", "### ")):
            continue
        if stripped.startswith(("- ", "* ")):
            lines.append(f"- {stripped[2:].strip()}")
        else:
            lines.append(f"- {stripped}")
    if len(lines) == 2:
        raise ValueError("Release notes did not produce any bullet lines for <Changes>")
    return "\n".join(lines).strip()


def release_heading(version: str, changelog: Path) -> str:
    heading = re.compile(
        rf"^##\s+(?:\[{re.escape(version)}\]\([^)]+\)|{re.escape(version)})(?:\s+-\s+(.+))?$"
    )
    for line in changelog.read_text().splitlines():
        match = heading.match(line.strip())
        if match:
            release_date = (match.group(1) or "").strip()
            if release_date:
                return f"### {release_date}"
            break
    return f"### {version}"


def encode_for_template(body: str) -> str:
    return html.escape(body, quote=False).replace("\n", "&#xD;\n")


def _next_version(repo: RepoConfig, *, component: str) -> str:
    if repo.publish_profile == "template":
        return next_semver_release_version(repo.path)
    config = component_config(repo, component)
    return next_aio_release_version(
        repo.path,
        repo.path / str(config.get("dockerfile", "Dockerfile")),
        repo.path / str(config.get("upstream_config", "upstream.toml")),
        suffix=str(config.get("release_suffix", "aio")),
        version_key=str(config.get("upstream_version_key", "UPSTREAM_VERSION")),
        tag_prefix=str(config.get("release_tag_prefix", "") or ""),
    )


def _version_revision(version: str, *, release_suffix: str) -> str:
    match = re.search(rf"-{re.escape(release_suffix)}\.(\d+)$", version)
    return match.group(1) if match else ""


def _release_xml_sources(repo: RepoConfig, *, component: str) -> list[str]:
    config = component_config(repo, component)
    xml_paths = config.get("xml_paths", [])
    if isinstance(xml_paths, str) and xml_paths.endswith(".xml"):
        return [xml_paths]
    if isinstance(xml_paths, list):
        component_xml = [str(path) for path in xml_paths if str(path).endswith(".xml")]
        if component_xml:
            return component_xml
    assets = repo.raw.get("catalog_assets", [])
    xml_sources = [
        str(asset.get("source", ""))
        for asset in assets
        if isinstance(asset, dict) and str(asset.get("source", "")).endswith(".xml")
    ]
    if xml_sources:
        return xml_sources
    return [path for path in repo.list_value("xml_paths") if path.endswith(".xml")]


def component_config(repo: RepoConfig, component: str) -> dict[str, object]:
    config: dict[str, object] = {
        "dockerfile": "Dockerfile",
        "upstream_config": "upstream.toml",
        "release_suffix": "aio",
        "upstream_version_key": repo.get("upstream_version_key", "UPSTREAM_VERSION"),
    }
    components = repo.raw.get("components")
    if isinstance(components, dict):
        component_config = components.get(component)
        if isinstance(component_config, dict):
            config.update(component_config)
            config.setdefault(
                "upstream_version_key",
                repo.get("upstream_version_key", "UPSTREAM_VERSION"),
            )
    return config
